sudo: required
services:
  - docker

before_install:
  - docker build -t sultanmyrza/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sultanmyrza/react-test npm test -- --coverage

after_success:
  - docker build -t sultanmyrza/multi-client ./client
  - docker build -t sultanmyrza/multi-nginx ./nginx
  - docker build -t sultanmyrza/multi-server ./server
  - docker build -t sultanmyrza/multi-worker ./worker
  # Login to the docker cli
  = echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  # Take those images and push them to docker hub
  - docker push sultanmyrza/multi-client 
  - docker push sultanmyrza/multi-nginx
  - docker push sultanmyrza/multi-server
  - docker push sultanmyrza/multi-worker
